### ISSUE TITLE
Release to 1.10.2?

### ISSUE THREAD

**Issue by LiskoSlayer63** [RoyCurtis/WorldBorder-Forge#1]
Do you possibly have time to re-release this for Minecraft version 1.10.2?

**Comment by draeath** [comment]
This project [has been abandoned.](https://www.reddit.com/r/feedthebeast/comments/463yrl/171018_abandoning_forgeautoshutdown/)

**Comment by alothmanmoe** [comment]
It is now updated, check curseforge
https://minecraft.curseforge.com/projects/worldborder-forge

**Comment by LiskoSlayer63** [comment]
@abused This is awesome, and that's why I'm sorry to tell you that I've already upgraded my whole server to version 1.12.2. I still love this plugin/mod and I can't wait it to be released for 1.11.x and 1.12.x versions. Keep up the good work!

**Comment by alothmanmoe** [comment]
Ill have 1.11.2-1.12.2 releases sometime this week-nextweek

**Comment by LiskoSlayer63** [comment]
@abused Perfect! I'll test them immediately when they're out.

**Comment by alothmanmoe** [comment]
And its updated, source is on github and its awaiting curse approval
